#!/bin/sh
#
# A pre-commit hook script that adds the compilation result to the commit
# if the code compiles successfully

echo  "===="
echo "Precommit: Compiling before commit"
echo  "===="

LOGFILE=precommit.log
npx tsc
RESULT="$?"
if [  "$RESULT" == "0" ]; then
	echo "Compiled successfully"
	git add bin/*.js
	exit 0
fi
echo "Compilation failed"
# This hook doesn't fail
exit 0