#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Custom hook: Compiling before commit"
npx tsc > precommit.log 2>&1
TSC_OUT=`cat  precommit.log`
rm precommit.log
if [  "$?" == "0" ]; then
	exit 0
fi
echo "Compilation failed"
echo $TSC_OUT
exit 1